[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mediawiki-agent"
version = "0.1.0"
description = "smolagent Tools for interacting with MediaWiki instances"
authors = [{name = "kmarekspartz"}]
dependencies = [
    "smolagents",
    "pywikibot"
]

[tool.hatch.build.targets.sdist]
exclude = ["/tests"]
