name: CI

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

x-python-steps: &python-steps
  - uses: actions/checkout@v3
  - name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ matrix.python-version }}
  - name: Install common dependencies
    run: |
      python -m pip install --upgrade pip

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - <<: *python-steps
    - name: Install lint dependencies
      run: |
        pip install .[lint]
    - name: Check formatting with Ruff
      run: |
        ruff format --check .
    - name: Lint with Ruff
      run: |
        ruff check .

  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - <<: *python-steps
    - name: Install typecheck dependencies
      run: |
        pip install -e .
        pip install .[typecheck]
    - name: Type check with mypy
      run: |
        mypy .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - <<: *python-steps
    - name: Install test dependencies
      run: |
        pip install pytest
        pip install -e .
        pip install -e .[test]
    - name: Run tests
      run: |
        pytest tests/
