name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .
        pip install .[lint]
        pip install -e .[test]

    - name: Check formatting with Ruff
      run: |
        ruff format --check .
    - name: Lint with Ruff
      run: |
        ruff check .
    - name: Type check with mypy
      run: |
        mypy .
    - name: Run tests
      run: |
        pytest tests/
